spring.application.name=kyc
server.port=8080

# DB
spring.datasource.url=jdbc:postgresql://localhost:5431/kycdb
spring.datasource.username=kyc
spring.datasource.password=kyc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Okunacak log dosyası
app.ingestion.log-path=D:/logs/app.log

# Kaç ms'de bir dosyayı kontrol edelim
app.ingestion.poll-ms=1000

# Batch insert boyutu (performans için)
app.ingestion.batch-size=200